### ISSUE TITLE
Import Error  on nodejs

### ISSUE THREAD

**Issue by xziy** [fabiospampinato/crypto-puzzle#2]
When i import by require
`const crypto_puzzle_1 = require("crypto-puzzle");`

 i get error

`Error [ERR_REQUIRE_ESM]: require() of ES Module `

i found way 

`let Puzzle = require("fix-esm").require("crypto-puzzle").default;`

but is not clean, please add support regular require

**Comment by fabiospampinato** [comment]
Sorry I switched to ESM only.
